### ISSUE TITLE
Als administrator kan ik nieuwe gebruikers aanmaken

### ISSUE THREAD

**Issue by JonasStaes** [JonasStaes/Business-Project-KAS#5]

**Comment by Saithamdb** [comment]
- [ ] FE: Component Admin aanmaken
- [ ] FE: Component gebruiker aanmaken
- [ ] FE: Gebruiker POST call
- [ ] FE: Snapshot Test Component Admin
- [ ] FE: Snapshot Test Component gebruiker aanmaken
- [ ] FE: Unit test gebruiker register POST call
- [ ] BE: E-mail service 
- [ ] BE: Gebruiker POST methode aanmaken
- [ ] BE: Gebruiker DTO aanmaken
- [ ] BE: Unit test gebruiker aanmaken
